#ifndef SMARTCAM_PERSON_DETECT_MODEL_H
#define SMARTCAM_PERSON_DETECT_MODEL_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Person detection model (quantized TFLite).
 *
 * Source: TensorFlow Lite Micro person_detect example
 *   https://github.com/tensorflow/tflite-micro
 *
 * To generate:
 *   1. Download person_detect.tflite from the TFLite Model Zoo
 *   2. Use xxd to convert: xxd -i person_detect.tflite > person_detect_model.cpp
 *      or use the TensorFlow Lite Micro Python export tool:
 *        python -c "
 * import tensorflow as tf
 * import numpy as np
 * converter = tf.lite.TFLiteConverter.from_saved_model('person_detect_model')
 * converter.optimizations = [tf.lite.Optimize.DEFAULT]
 * tflite_model = converter.convert()
 * with open('person_detect_model.tflite', 'wb') as f:
 *     f.write(tflite_model)
 * "
 *   3. Place the generated .cpp file alongside this header
 *   4. Declare the symbols here
 *
 * Expected syms (generated by xxd):
 *   unsigned char g_person_detect_model_data[]
 *   unsigned int g_person_detect_model_data_len
 *
 * When the model .cpp is not linked, define SMARTCAM_PERSON_DETECT_MODEL_STUB
 * to use a minimal placeholder that compiles but always returns "no person".
 */

extern const unsigned char g_person_detect_model_data[];
extern const unsigned int g_person_detect_model_data_len;

#ifdef __cplusplus
}
#endif

#endif
